[package]
name = "dumbgame"
version = "0.1.0"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = "0.3.18"
legion = {git = "https://github.com/TomGillen/legion.git", default-features = false}

[profile.release]
opt-level = 3
lto = true
debug = true
debug-assertions = false